import { writeFile } from "node:fs/promises"
import { type BetterAuthOptions, logger } from "better-auth"
import { type RemultAdapterOptions, remultAdapter } from "./remult-ba"

export async function generateRemultSchema({
	options,
	file,
	adapterOptions = {},
}: {
	options: BetterAuthOptions
	file: string
	adapterOptions?: Omit<RemultAdapterOptions, "authEntities">
}) {
	const adapter = remultAdapter({
		...adapterOptions,
		// for schema generation, we don't need to declare entities.
		authEntities: {},
	})(options)

	if (!adapter.createSchema) {
		throw new Error(`Adapter "${adapter.id}" does not support createSchema`)
	}

	const { code, path, overwrite } = await adapter.createSchema(options, file)

	const genTimestamp = (() => {
		const ts = new Date()
		return `${ts.toISOString()} | ${ts.toLocaleString("en-US", { timeZone: "America/Los_Angeles", timeZoneName: "short" })}`
	})()

	const pre = ["//".repeat(10), `// GENERATED by remult-better-auth. ${genTimestamp}`, "//".repeat(10)].join("\n")
	const post = ["", "//".repeat(10), `// END GENERATED by remult-better-auth. ${genTimestamp}`, "//".repeat(10)].join(
		"\n"
	)

	logger.info("Writing remult entities to:", path)
	const content = [overwrite ? pre : `\n${pre}`, code, post].join("\n")
	await writeFile(path, content, { encoding: "utf-8", flag: overwrite ? "w+" : "a" })
	return path
}
